<?php

declare(strict_types=1);
/**
 * This file is part of SuAdmin.
 *
 * @link     https://www.SuAdmin.com
 * @document https://doc.SuAdmin.com
 * @contact  yqhcode@qq.com
 * @license  https://github.com/su-suan/suadmin
 */

namespace SuAdmin\Command;

use Hyperf\Command\Annotation\Command;
use SuAdmin\SuAdminCommand;

/**
 * Class SuAdmin.
 */
#[Command]
class SuAdmin extends SuAdminCommand
{
    protected ?string $name = 'suadmin';

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * Handle the current command.
     */
    public function handle()
    {
        $result = shell_exec('php ' . BASE_PATH . '/bin/hyperf.php | grep suadmin');
        $this->line($this->getInfo(), 'comment');
        $this->line(preg_replace('/\s+suadmin\s+/', '', $result), 'info');
    }
}
